project_id: "531392"
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /content/en/**/*
    translation: /content/%locale%/**/%original_file_name%

  - source: /data/en/**/*
    translation: /data/%locale%/**/%original_file_name%
