name: Deploy Starlight Docs
on:
  push:
    branches:
      - v3-alpha
    paths:
      - 'docs/**/*'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    defaults:
      run:
        working-directory: ./docs  # Set working directory to docs

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: docs/package-lock.json

      # Cache npm dependencies
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Cache Astro build
      - name: Cache Astro build
        uses: actions/cache@v3
        with:
          path: |
            dist
            .astro
          key: ${{ runner.os }}-astro-build-${{ hashFiles('src/**/*') }}
          restore-keys: |
            ${{ runner.os }}-astro-build-

      - name: Install dependencies
        run: npm ci

      - name: Build Starlight site
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
